<a href="https://colab.research.google.com/github/shanfty/CS_5265_ML_Project/blob/main/CS_5262_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook for ML

Describe my project in a text cell including the following sections:


Background

The Dataset will be looking at a popular online car marketplace known as cars.com. The dataset is from kaggle.com, https://www.kaggle.com/datasets/chancev/carsforsale There is around 9000 data points for different cars including their descriptions and prices for the listings.


Project Description

The project will first be to clean up data, to make sure all the variables can be transformed into the correct class. Looking at the car's features and predicting a price, or vice versa. Taking in some examples of certain features of a car and its price and guessing which other features it has or the ratings it has on the cars.com catelog. Can even look into private vs dealership sales and the different between features & prices of the two. Most likely creating a regression model that predicts a car's price. Future steps could be to look at past years catelogs to see how much the market has been effected from the last couple of years for inflation wise.


Performance Metrix

Looking at the predicted valuation of the car vs the actual price listed. Need to have a range and not be exact because listing price does not neccessarly mean its worth that much or little. Thinking plus or mins $250 to determine if the predicted value is successful. Then look at all the success to find the accuracy of the algorithm.

## Feature Engineering

## Importing Libraries

In [ ]:
# tables and visualizations
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Loading Data

In [22]:
data_dictionary = pd.read_csv("https://docs.google.com/spreadsheets/d/1A5GPct-AqzSzEFbDWKczS6eKnS3zTV3cLkyWxNBYKrA/export?format=csv&grid=")

display(data_dictionary)

                  Feature                                        Description
0                    Year  What year the car model was made in. Stander 4...
1                    Make  The dealer of the car, who created the company...
2                   Model  The model of the car, Spaces and dashes used n...
3                Used/New            String 2 options, 'used' or 'certified'
4                   Price    Price of the car following this format $xxx,xxx
5          ConsumerRating  Rating that the consumer of the car has given ...
6         ConsumerReviews  How many reviews consumers have given. Straigh...
7              SellerType  Sold from a dealer or private individual, 2 st...
8              SellerName  The name of the Seller, can be pretty long wit...
9            SellerRating  The rating the seller gives to the vehicle 0.0...
10          SellerReviews   how many reviews the seller has given, no commas
11             StreetName  The Street of where the vehicle is being sold,...
12                  State  The state code of where the vehicle is being s...
13                Zipcode  the zipcode where the car is being sold. Split...
14               DealType  A cars.com classification if the vehicle price...
15          ComfortRating  The rating of the comfortability for the vehic...
16   InteriorDesignRating  The rating of the design and feel for the insi...
17      PerformanceRating  the rating for the performance of the vehicle ...
18    ValueForMoneyRating  A rating from 0.0 - 5 on how good of a car you...
19  ExteriorStylingRating  The rating of the exterior looks of the vehicl...
20      ReliabilityRating           How reliable the vehicle is from 0.0 - 5
21          ExteriorColor  The exterior color the car is. Spaces and dash...
22          InteriorColor  The interior color of the car. Spaces and slas...
23             Drivetrain         3 digit string, 'FWD', 'RWD', 'AWD', '4WD'
24                 MinMPG  1 to 3 digit number describing the min miles p...
25                 MaxMPG  1 to 3 digit number describing the max miles p...
26               FuelType  There are really 4 types, Gasoline, desiel, hy...
27           Transmission  What type of transmissions the vehicle is runn...
28                 Engine  What type of engine is in the vehicle. Numbers...
29                    VIN  The Vehicle Identification number every one is...
30                 Stock#  The stock number of the vehicle, Probably do n...
31                Mileage  How many miles are the vehicle has already bee...

In [ ]:
cars = pd.read_csv("https://docs.google.com/spreadsheets/d/1L-jeVC6ujsiOxCZ578ngfKm1iuimJOyw8HOz765WVOM/export?format=csv&grid=")

display(cars.tail(5))
cars.info()

,Year,Make,Model,Used/New,Price,ConsumerRating,ConsumerReviews,SellerType,SellerName,SellerRating,...,InteriorColor,Drivetrain,MinMPG,MaxMPG,FuelType,Transmission,Engine,VIN,Stock#,Mileage
9374,2019,Subaru,Crosstrek 2.0i Premium,Used,"$27,374",4.7,205,Dealer,Bertera Subaru of West Springfield,4.4,...,Gray,All-wheel Drive,27,33,Gasoline,Automatic CVT,2.0L H4 16V GDI DOHC,JF2GTADC4KH318032,220502A,15606
9375,2019,Audi,Q8 3.0T Premium,Used,"$61,998",4.8,27,Dealer,Autobahn USA Westborough,4.8,...,Black,All-wheel Drive,17,22,Hybrid,8-Speed Automatic,3.0L V6 24V GDI DOHC Turbo Hybrid,WA1AVAF14KD015389,AB4719,46855
9376,2017,Buick,Enclave Leather,Used,"$26,944",4.8,137,Dealer,Tulley Automotive Group,4.7,...,Ebony,All-wheel Drive,15,22,Gasoline,6-Speed Automatic,3.6L V6 24V GDI DOHC,5GAKVBKD4HJ190334,B221381B,62649
9377,2019,Subaru,Forester Premium,Used,"$28,568",4.7,279,Dealer,Ira Subaru,4.4,...,Black,All-wheel Drive,26,33,Gasoline,Automatic CVT,2.5L H4 16V GDI DOHC,JF2SKAGC9KH423450,KH423450,30760
9378,2019,Hyundai,Santa Fe Ultimate 2.4,Used,"$32,091",4.8,204,Dealer,Route 44 Hyundai,4.4,...,Black,All-wheel Drive,21,27,Gasoline,8-Speed Automatic,2.4L I4 16V GDI DOHC,5NMS5CAD1KH002128,H48345,41645

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9379 entries, 0 to 9378
Data columns (total 32 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   9379 non-null   int64
 1   Make                   9379 non-null   object
 2   Model                  9379 non-null   object
 3   Used/New               9379 non-null   object
 4   Price                  9379 non-null   object
 5   ConsumerRating         9379 non-null   float64
 6   ConsumerReviews        9379 non-null   int64
 7   SellerType             9379 non-null   object
 8   SellerName             9379 non-null   object
 9   SellerRating           9379 non-null   float64
 10  SellerReviews          9379 non-null   int64
 11  StreetName             9379 non-null   object
 12  State                  9379 non-null   object
 13  Zipcode                9379 non-null   object
 14  DealType               9157 non-null   object
 15  ComfortRating          9379 non-null   float64
 16  InteriorDesignRating   9379 non-null   float64
 17  PerformanceRating      9379 non-null   float64
 18  ValueForMoneyRating    9379 non-null   float64
 19  ExteriorStylingRating  9379 non-null   float64
 20  ReliabilityRating      9379 non-null   float64
 21  ExteriorColor          9379 non-null   object
 22  InteriorColor          9379 non-null   object
 23  Drivetrain             9379 non-null   object
 24  MinMPG                 9379 non-null   int64
 25  MaxMPG                 9379 non-null   int64
 26  FuelType               9379 non-null   object
 27  Transmission           9379 non-null   object
 28  Engine                 9379 non-null   object
 29  VIN                    9379 non-null   object
 30  Stock#                 9379 non-null   object
 31  Mileage                9379 non-null   int64
dtypes: float64(8), int64(6), object(18)
memory usage: 2.3+ MB

In [ ]:
cars['Drivetrain'].value_counts()

All-wheel Drive      4476
Front-wheel Drive    2329
Four-wheel Drive     1549
Rear-wheel Drive      915
FWD                    36
AWD                    34
4WD                    20
RWD                    12
–                       7
Front Wheel Drive       1
Name: Drivetrain, dtype: int64

## Assignment 3 Task 2
1. I would like to fix up the drive train field. Currently there are mulitple options ranging from spelling out the words to using abreviations in the data. IE. Front-Wheel drive vs FWD. This is an issue because in reality there is only 4 options but the data is showing around 10 different options. Will need to set it all to FWD, AWD, RWD, 4WD. 
2. Next would be looking at the zip code. There are some categories in the zipcode that are alphebetical and not numberical. These will either have to be converted or removed from the data.
3. A third thing that needs to be looked at is the Used/New data field. This is showing used or [make] certified. I.E. 'Dodge Certified' So there is multiple entries for each brand when in reality it should just read new, change all these to new or just certified we already have a make field.
4. In both the interior and exterior color data field there are weird symbols and entries that have 'â€“' in it. These will have to be removed or replaced.

## Assignment 3 Basic EDA
1. Drop the Street address since we already have the state and a zipcode
2. Fixing driveline field so it is only in the 4 options listed above
3. Take all everything with 'certified' in it in the used/new data field and replace it with just new.

## A3 Train test Split
Having a ~9k entries will split into using 70% for training and 30% for testing. Would like to train more since testing doesn't need that many cars.

## A3 Initial Pipeline
Standardization for variables, Choosing what models to show the data. Cycling through pipelines add more to transform data based on the models or adding new features.

## Model Fitting & Evaluation
I antcipate the model will have performance that is close to the actual price listed in the data. I am hoping for 10% within the actual price. I am suspecting the engine column might not have that big of an effect as it should, since each engine is labeled something different. it's not just standard v8 or v8, v10 supercharged. Maybe having a feature for HP would be more beneficial.